### ISSUE TITLE
Cannout find module rimraf

### ISSUE THREAD

**Issue by xdumaine** [trentmwillis/ember-exam#64]
It looks like `rimraf` is listed as a dev dependency, but should be listed as a regular dependency. When running `ember exam:iterate`, it ends with 

```text
Cannot find module 'rimraf'
Error: Cannot find module 'rimraf'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at CoreObject.module.exports._cleanupBuild (/Users/xanderdumaine/Code/web-directory/node_modules/ember-exam/lib/commands/exam/iterate.js:84:18)
```

**Comment by trentmwillis** [comment]
Will release a new version with this fix this evening (mobile right now)
